### Tambah kelas
POST http://localhost:5000/api/kelas/
Content-Type: application/json

{
    "guru_id": 1,
    "nama_kelas": "Kelas 3A",
    "tingkatan": "3"
}

### Ambil semua kelas guru
GET http://localhost:5000/api/kelas/?guru_id=1