### Tambah siswa
POST http://localhost:5000/api/siswa/
Content-Type: application/json

{
  "kelas_id": 1,
  "nama": "Budi Santoso"
}

### Ambil semua siswa
GET http://localhost:5000/api/siswa/?kelas_id=1